DROP TABLE IF EXISTS PRICES;
CREATE TABLE IF NOT EXISTS PRICES (
ID IDENTITY NOT NULL PRIMARY KEY,
BRAND_ID INT NOT NULL,
START_DATE TIMESTAMP NOT NULL,
END_DATE TIMESTAMP NOT NULL,
PRICE_LIST INT NOT NULL,
PRODUCT_ID INT NOT NULL,
PRIORITY INT NOT NULL,
PRICE DECIMAL(4,2) NOT NULL,
CURR CHAR(3) DEFAULT 'EUR' NOT NULL
);